FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app/
EXPOSE 80

CMD ["fastapi", "run", "main.py", "--port", "80"]
